wa72_json_rpc:
    functions:
        get_hot_deals:
            service: "wsh_lapi.content"
            method: "getHotDeals"
        get_featured:
            service: "wsh_lapi.content"
            method: "getFeaturedOffers"
        register_device:
            service: "wsh_lapi.users"
            method: "registerDevice"
        unregister_device:
            service: "wsh_lapi.users"
            method: "unRegisterDevice"
        update_user:
            service: "wsh_lapi.users"
            method: "updateUser"
        post_alert:
            service: "wsh_lapi.alerts"
            method: "postAlert"
        delete_alert:
            service: "wsh_lapi.alerts"
            method: "deleteAlert"
        update_alert:
            service: "wsh_lapi.alerts"
            method: "updateAlert"
        get_ofers_for_alert:
            service: "wsh_lapi.alerts"
            method: "getAllOffersForAlert"
        get_user_alerts:
            service: "wsh_lapi.alerts"
            method: "getUserAlerts"
        testhello:
            service: "wa72_jsonrpc.testservice"
            method: "hello"
        register_sales_lead:
            service: "wsh_lapi.users"
            method: "registerSalesLead"
        set_read_status:
            service: "wsh_lapi.alerts"
            method: "setReadStatus"