wa72_json_rpc:
    functions:
        get_hot_deals:
            service: "wsh_lapi.content"
            method: "getHotDeals"
        get_featured:
            service: "wsh_lapi.content"
            method: "getFeaturedOffers"
        register_device:
            service: "wsh_lapi.users"
            method: "registerDevice"
        unregister_device:
            service: "wsh_lapi.users"
            method: "unRegisterDevice"
        update_user:
            service: "wsh_lapi.users"
            method: "updateUser"
        post_alert:
            service: "wsh_lapi.alerts"
            method: "postAlert"
        delete_alert:
            service: "wsh_lapi.alerts"
            method: "deleteAlert"
        update_alert:
            service: "wsh_lapi.alerts"
            method: "updateAlert"
        get_offers_for_alert:
            service: "wsh_lapi.alerts"
            method: "getAllOffersForAlert"
        get_updated_offers_for_alert:
            service: "wsh_lapi.alerts"
            method: "getAllUpdatedOffersForAlert"
        get_user_alerts:
            service: "wsh_lapi.alerts"
            method: "getUserAlerts"
        testhello:
            service: "wa72_jsonrpc.testservice"
            method: "hello"
        register_sales_lead:
            service: "wsh_lapi.users"
            method: "registerSalesLead"
        set_read_status:
            service: "wsh_lapi.alerts"
            method: "setReadStatus"
        get_number_of_pages_for_alert:
            service: "wsh_lapi.alerts"
            method: "getNumberOfPages"
        set_as_favourite:
            service: "wsh_lapi.content"
            method: "setAsFavourite"
        get_amount_of_fav_for_offer:
            service: "wsh_lapi.content"
            method: "getAmountOfFavForOffer"
        get_user_fav_offers:
            service: "wsh_lapi.content"
            method: "getUserFavOffers"
        send_test_notification:
            service: "wsh_lapi.users"
            method: "sendTestNotification"