wsh_lapi_backend:
    resource: "@WshLapiBackendBundle/Controller/"
    type:     annotation
    prefix:   /backend

wa72_json_rpc:
    resource: "@Wa72JsonRpcBundle/Resources/config/routing.yml"
    prefix:   /jsonrpc