wsh_lapi_backend:
    resource: "@WshLapiBackendBundle/Controller/"
    type:     annotation
    prefix:   /admin

wa72_json_rpc:
    resource: "@Wa72JsonRpcBundle/Resources/config/routing.yml"
    prefix:   /jsonrpc

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

admin_wsh_lapi_offer_create:
    pattern:  /admin/wsh/lapi/offer/import
    defaults: { _controller: WshLapiBackendBundle:Admin:importOffer }

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin