<?php

namespace Wsh\LapiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OfferReadStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferReadStatusRepository extends EntityRepository
{
}
