<?php

namespace Wsh\LapiBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends EntityRepository
{
    public function findOfferWithIdLike($id) {
        $qb = $this->_em->createQueryBuilder();

        $query = $qb
            ->select("o")
            ->from('Wsh\LapiBundle\Entity\Offer', 'o')
            ->where($qb->expr()->like("o.id", $qb->expr()->literal("%".$id."%")))
            ->getQuery();

        return $query->getResult();

    }
}
