<?php

namespace Wsh\LapiBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OfferFavRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferFavRepository extends EntityRepository
{
}
