<?php

namespace Wsh\LapiBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OfferUpdateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferUpdateRepository extends EntityRepository
{
}
